# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\python_project\ui\my_wedget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.btn_send = QtWidgets.QPushButton(Form)
        self.btn_send.setGeometry(QtCore.QRect(140, 50, 75, 23))
        self.btn_send.setObjectName("btn_send")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "窗口"))
        self.btn_send.setText(_translate("Form", "按钮"))
